### ISSUE TITLE
哥哥们，这默认的后台帐号密码多少啊

### ISSUE THREAD

**Issue by chinacc** [zhiyicx/thinksns-plus#11]
哥哥们，这默认的后台帐号密码多少啊

**Comment by this-BaiShi** [comment]
123456

**Comment by medz** [comment]
关闭这个没有意义的issue。

Seven Du <lovevipdsw@outlook.com<mailto:lovevipdsw@outlook.com>>

在 2017年3月24日，22:52，白石 <notifications@github.com<mailto:notifications@github.com>> 写道：


123456

**Comment by medz** [comment]
最新的ts+默认账户
admin admin
仅限后台可以此方式登录，app或者spa登录请先进入后台修改手机号码后可登录。
