### ISSUE TITLE
composer安装依赖错误

### ISSUE THREAD

**Issue by mxh861001** [zhiyicx/thinksns-plus#19]
### Description:
composer安装依赖的时候
 [ErrorException]
  ZipArchive::extractTo(D:\phpStudy\wwwroot\thinksns-plus/vendor/composer/6d15e
  4ee/zhiyicx-plus-component-feed-acef364\documents/Feed娑堟伅瀵圭収琛?md): failed to open stream: Invalid argument

**Comment by medz** [comment]
你的系统不支持中文～

**Comment by medz** [comment]
@scrubmx 已经安排人讲中文文件名改成英文。

**Comment by medz** [comment]
已经修改～
