### ISSUE TITLE
服务器返回头信息讨论后的处理流程图

### ISSUE THREAD

**Issue by LipYoung** [zhiyicx/thinksns-plus#2]
![15acf6c7-06ca-4dab-909e-dc0e85fef8c1](https://cloud.githubusercontent.com/assets/15086314/21512741/7f780e5e-cceb-11e6-8ebb-693db55aa3fb.png)

**Comment by boxshadow** [comment]
Code must not be 0 when status is false

**Comment by medz** [comment]
https://github.com/zhiyicx/thinksns-plus/blob/master/documents/api/v1/%E8%87%AA%E5%8A%A8%E8%AE%A4%E8%AF%81%E6%A6%82%E8%BF%B0.md
