### ISSUE TITLE
用户关注数量错乱。

### ISSUE THREAD

**Issue by peicaichi** [zhiyicx/thinksns-plus#20]
- TS+ Version: later

### Description:

刷新后列表上其他人状态也显示未关注，且点击到其他人的主页，也显示未关注，但是在我的关注列表里却有此人

### Steps To Reproduce:

首页-动态详情-点赞榜-取消关注其中一个人-刷新

- [ ] 修复关注数量错乱的bug

**Comment by guweigang** [comment]
有demo可以看吗？

**Comment by zhiyicx-developer** [comment]
您好，由于目前整个程序没有web页面，只有后台，所以暂时没有demo可以看。只演示后台没有意义，而且，我们是等到 SPA 开发完直接上 SPA 作为演示。pc目前正在弱化，这个 ThinkSNS+ 是只提供API的程序。
如果严格的说测试站，邀请测试的服务器 http://test-plus.zhibocloud.cn 这个应该算演示站。对于用户而言，我们的体验站已经发布了，用户下载 app 体验。后端 API部分其实本身没必要上线。如果您需要体验APP的话，您可以发邮件至我们的相关人员处：内测申请方式

　　提供个人／企业联系方式及认证信息（实名ID／企业营业执照照片或扫描件）及申请说明，发送邮件至lihecong@zhishisoft.com将有机会获得首批内测资格，名额有限，申请从速。

　　参与内测请提供以下资料

　　1个可接收验证码的手机号

　　1个指定邮箱

　　1位测试人员姓名

　　1个您喜欢的账号昵称
 
 
------------------ Original ------------------
From: "顾伟刚"; 
Date: 2017年5月3日(星期三) 中午1:44
To: "zhiyicx/thinksns-plus"; 
Cc: "Subscribed"; 
Subject: Re: [zhiyicx/thinksns-plus] 用户关注数量错乱。 (#20)

 

有demo可以看吗？

**Comment by this-BaiShi** [comment]
已使用组合键保证数据表数据一致，运行一周未发现问题
