### ISSUE TITLE
【消息】同一个人回复评论，消息通知显示了两个名字

### ISSUE THREAD

**Issue by peicaichi** [zhiyicx/thinksns-plus#24]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:
同一个人回复评论，消息通知显示了两个名字。例：“A，A，评论了我”

### Fixed step:
A评论B的动态-B回复两次A-A查看消息
- [ ] fixed.

**Comment by this-BaiShi** [comment]
该问题需要移动端处理
