### ISSUE TITLE
功能优化：创建新用户时，可以直接给该用户选择用户组

### ISSUE THREAD

**Issue by hantianlong** [zhiyicx/thinksns-plus#27]
创建新用户时，可以直接给该用户选择用户组，勾选完毕后，可回到“”“用户管理”信息列表，也可跳转到用户详情页进行编辑，编辑完成后，回到”“用户管理”信息列表。
原因：从运营层面讲，很多用户添加用户时，除了基本的用户名，手机号，密码外，划归用户组属于第一步操作范畴

**Comment by medz** [comment]
已经在 https://github.com/zhiyicx/thinksns-plus/commit/2c62f851c019d6024496e8216ed553980b28f0f2 做了修改，跳转到用户编辑页面。
添加普通用户通常是不需要添加用户组的，添加管理用户属于少数情况，所以跳转到用户编辑页面，进行深度定制用户资料。

**Comment by hantianlong** [comment]
1
