### ISSUE TITLE
用户管理信息列表，按照时间倒叙排序用户信息，即新注册的在前面

### ISSUE THREAD

**Issue by hantianlong** [zhiyicx/thinksns-plus#28]
目前是正序排序，不利于新用户数据查看和管理

**Comment by medz** [comment]
大哥。。。搜索功能呀。可以按照排序搜索。

**Comment by medz** [comment]
见图：
<img width="536" alt="qq20170509-173438 2x" src="https://cloud.githubusercontent.com/assets/5564821/25844682/d12be496-34dd-11e7-9168-9791a0c16eff.png">

**Comment by hantianlong** [comment]
我是说默认的顺序改成倒叙展示 我知道有搜索功能，现在是默认正序

**Comment by medz** [comment]
修改以及提交，默认倒序。
