### ISSUE TITLE
不确定是否是接口问题：地区库添加  韩国 -首尔，但是app端修改地址的时候这个地区选项出不来

### ISSUE THREAD

**Issue by hantianlong** [zhiyicx/thinksns-plus#30]
![1](https://cloud.githubusercontent.com/assets/28078379/25845193/a2ba8566-34df-11e7-87a4-c1f989008884.png)

**Comment by medz** [comment]
这个我确实要关闭。。这个让app解释吧～算了，我解释吧～他们没有用后台的地区数据，他们自己用的本地的。

**Comment by LipYoung** [comment]
之前讨论过,每次需要更新地址的情况下,由后台配置并且到处地区配置信息.手动替换本地包
@hantianlong
