### ISSUE TITLE
访问后台网页奔溃

### ISSUE THREAD

**Issue by iScript** [zhiyicx/thinksns-plus#33]
- TS+ Version: github clone的最新版
- PHP Version: 7.0
- Database Driver & Version: mysql 5.6

### Description:

php artisan serv 启动后，访问首页是正常的，访问后台就网页一直在转圈，过一段时间后就奔溃了

![8285782a-1856-4d5b-98fa-81793fbc750e](https://cloud.githubusercontent.com/assets/2595251/25881291/a39b8144-356e-11e7-83c7-e1e723b7ca3d.png)

**Comment by medz** [comment]
进入vue-router 死循环了，已经修复，请
```shell
git pull
```
即可解决。
