### ISSUE TITLE
拓展应用开发疑问？

### ISSUE THREAD

**Issue by 1459416736** [zhiyicx/thinksns-plus#34]
你好，首先感谢你们的开源项目，我现在研究了下，针对开发你们的拓展应用这块不是很明白，文档写的很简单，能否进行下步骤说明呢？

**Comment by medz** [comment]
你好，目前正在完善文档，因为开发时间比较紧。你可以先参考下已完成的模块，其实就是配置一个 installer 很简单的。其他的均是应用自己实现。

**Comment by 1459416736** [comment]
拓展应用开发好了测试是否必须发布到github，然后在进行安装测试么？

**Comment by medz** [comment]
@1459416736 有内置开发模式，可以模拟完整的的composer打包过程，你看有一个命令叫做 
```shell
php artisan component:archive
```
就是用来打包的，运行命令打包你的拓展后，完全可以正常的走 require 等流程

**Comment by medz** [comment]
@1459416736 https://github.com/zhiyicx/thinksns-plus/blob/master/documents/component/built-in-development-support.md 看下这个文档，你就明白了。

**Comment by 1459416736** [comment]
ok,thinks

**Comment by medz** [comment]
@1459416736 https://github.com/zhiyicx/thinksns-plus/tree/master/docs/package 拓展开发文档已经齐全。
