### ISSUE TITLE
V2 版本接口无法处理 多设备登陆情况

### ISSUE THREAD

**Issue by LipYoung** [zhiyicx/thinksns-plus#37]
当用户多设备登陆导致需要重新登录时,返回的信息内容"多设备登陆"和普通的错误返回信息内容格式一致.致使移动端无法根据该特殊情况作出不同于普通错误信息的处理.

**Comment by LipYoung** [comment]
移动端有一个需求 当用户被挤下线时,需要显示具体的原因.例如"多设备登陆",""验证信息过期"等
目前服务端不能返回"多设备登陆"这个错误码

**Comment by medz** [comment]
@LipYoung 周末深入研究了 oauth 后，发现一个问题，我们的 授权访问令牌 （access token）是有授权时间的，即使我们设定是永不过期，所以，在授权有效期内，授权访问令牌 失效，代表从其他地方登录了，只有过了有效期才失效为 令牌失效，客户端均以这一原则进行提示。

**Comment by LipYoung** [comment]
"多设备登陆" 咋办 @medz

**Comment by medz** [comment]
多设备登录不是你们处理的，你们只要按照这一原则处理即可，多设备的情况，我们后端不会下线其他设备的授权访问令牌。

**Comment by medz** [comment]
有时候问题就是被想的复杂了。而不是问题本身很复杂。

**Comment by LipYoung** [comment]
等回头修改这一块的时候按照你说的来。目前讨论就这样结束吧。
