### ISSUE TITLE
启动信息接口 返回的TS助手 ID 格式不正确

### ISSUE THREAD

**Issue by LipYoung** [zhiyicx/thinksns-plus#42]
![image](https://cloud.githubusercontent.com/assets/15086314/26196550/e2bf8b5c-3bf1-11e7-9f08-00f1981741cd.png)
![image](https://cloud.githubusercontent.com/assets/15086314/26196579/f617a428-3bf1-11e7-991c-20db90b4171f.png)

不符合要求的格式

**Comment by medz** [comment]
进入后台重新设置助手。

**Comment by medz** [comment]
这里的修复是指只是把修复提交到了 master
