### ISSUE TITLE
安装链接失效了

### ISSUE THREAD

**Issue by jalenjie** [zhiyicx/thinksns-plus#50]
RT

**Comment by LipYoung** [comment]
请提供更多的信息.谢谢

**Comment by jalenjie** [comment]
README 中的 安装链接.
https://github.com/zhiyicx/thinksns-plus/blob/master/docs/get-started/installed.md  no found

**Comment by medz** [comment]
@jalenjie 好的，收到，readme 忘记更新地址了～

**Comment by medz** [comment]
文档已经增加～

**Comment by jalenjie** [comment]
安装完后 首页返回 “ThinkSNS+” 。 后台可以进。
