### ISSUE TITLE
后台登录问题  登录失败？

### ISSUE THREAD

**Issue by jlala** [zhiyicx/thinksns-plus#52]
后台账号密码 都为root吧？
现在输入root 提示登录失败

还有就是 需要执行迁移数据表 和填充数据吗？ 这个出错了呢

**Comment by medz** [comment]
你有填充数据吗？

**Comment by jlala** [comment]
![image](https://user-images.githubusercontent.com/8163601/27259032-4a15e924-543c-11e7-8fd8-7a74c4857cdc.png)
没有填充 还在最后阶段呢

**Comment by medz** [comment]
需要运行数据填充后才能进入后台的

**Comment by jlala** [comment]
我是容器 启动的 这里的 db_host 应该写什么呢？
基本 .env没怎么修改 ，都是按照教程来的

**Comment by medz** [comment]
@jlala 你是用的 laradock 吗？如果是 db_host 就直接写 mysql

**Comment by jlala** [comment]
对是用的 loardock 现在迁移数据表 报错 [PDOException]
  SQLSTATE[HY000] [2002] Connection refused

**Comment by medz** [comment]
给我看下你的配置

**Comment by medz** [comment]
你输入 `docker-compose ps` 截图我看下·

**Comment by jlala** [comment]
![image](https://user-images.githubusercontent.com/8163601/27259059-0f2dd4c4-543d-11e7-8b78-faacf939a812.png)

**Comment by medz** [comment]
截图下你现在 的 ts+ .env 配置

**Comment by jlala** [comment]
我原来本机 安装过mysql，后来 docker里面的mysql提示端口占用，所以我就把本机的mysql停止运行了，然后docker的mysql通过端口问题了

**Comment by medz** [comment]
你在工作区 ping mysql 试一下～看能不能通～

**Comment by jlala** [comment]
![image](https://user-images.githubusercontent.com/8163601/27259083-8064038e-543d-11e7-852d-591bb525023f.png)
![image](https://user-images.githubusercontent.com/8163601/27259085-8aba221e-543d-11e7-9721-5363e8c1b82c.png)

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/27259089-a232fb0a-543d-11e7-8bab-b2f398db7572.png)
你的配置不对，修改成类似：
![image](https://user-images.githubusercontent.com/5564821/27259098-c96176fc-543d-11e7-8ce3-649f991b337e.png)
你的host还是 127.0.0.1 肯定连接不上的

**Comment by medz** [comment]
还有就是 database 一定要保证数据库是存在的空数据库哟，还有 laradock 的mysql 默认最该权限账户密码 是 `-u root -p root`

**Comment by jlala** [comment]
好的 我看下 刚才的问题对了，现在确实有报错说是 password: NO

**Comment by jlala** [comment]
laradock 里面的mysql 在哪里啊

**Comment by medz** [comment]
这个是别名主机～类似 hosts

**Comment by medz** [comment]
@jlala 在 docker-componse.yml 最后的地方配置的～

**Comment by jlala** [comment]
好 我看下配置文件

**Comment by medz** [comment]
好的～ 有问题继续评论，我们继续聊这个 docker 的东西，我自己也是用 docker 做环境的～

**Comment by jlala** [comment]
再问下 database 的数据库是在 ts+里面的database里面创建一个 数据库目录吗？

**Comment by medz** [comment]
不是的，例如你运行的是mysql，就进入 mysql 创建一个数据库～

**Comment by medz** [comment]
laradock 你运行的肯定是 mysql，你可以执行 `docker-compose up phpmyadmin` 输入 `网址:8080` 用 phomyadmin 建立一个空数据库的。

**Comment by jlala** [comment]
ok 好的 我是 找了半天不知道 mysql在我容器的哪里。。。汗颜呀

**Comment by medz** [comment]
进入 mysql 容器？和你进入 workspace 一样的，你只需要执行 `docker-compose exec mysql bash` 就可以了～

**Comment by medz** [comment]
但是不推荐进入 mysql 的容器，因为有工作区就够了，你可以用数据库管理软件，连接你的数据库管理。

**Comment by jlala** [comment]
嗯 我知道了 我一直在 工作区找mysql。。。其实 他是在laradock下，以前安装过dock但没怎么深入了解过

**Comment by medz** [comment]
每一个软件都是独立的容器隔离开运行的
例如你在命令行的php是工作区容器下的，而你网站是在 fpm 容器下的，都是被隔离开的，这样更安全。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月18日，16:28，jlala <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯 我知道了 我一直在 工作区找mysql。。。其实 他是在laradock下，以前安装过dock但没怎么深入了解过

**Comment by jlala** [comment]
mysql的数据库排序规则 设置成哪个呢？

**Comment by medz** [comment]
utf8mb4_unicode_ci

**Comment by jlala** [comment]
表创建好了，最后一步了 怎么步步都感觉得请教呢
![image](https://user-images.githubusercontent.com/8163601/27259373-7356170c-5444-11e7-9e75-e85a12ae5c73.png)

**Comment by medz** [comment]
哈哈哈 是 db：seed

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月18日，16:37，jlala <notifications@github.com<mailto:notifications@github.com>> 写道：


表创建好了，最后一步了 怎么步步都感觉得请教呢
[image]<https://user-images.githubusercontent.com/8163601/27259373-7356170c-5444-11e7-9e75-e85a12ae5c73.png>

**Comment by jlala** [comment]
哈哈 改下你的md呀  误导小白啦，还有前面的 docker0compose  -> docker-compose
cp env.example .env && vi .env -》 cp .env.example .env && vi .env

**Comment by jlala** [comment]
好了呢 进来了

**Comment by medz** [comment]
关于使用 docker 方式部署本身写的比较笼统，因为用这种方式的大多肯定都是了解并熟练使用docker哈哈

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月18日，16:40，jlala <notifications@github.com<mailto:notifications@github.com>> 写道：


哈哈 改下你的md呀 误导小白啦，还有前面的 docker0compose -> docker-compose
cp env.example .env && vi .env -》 cp .env.example .env && vi .env

**Comment by jlala** [comment]
还有一个地方请教下。
我在 thinksns-plus 这个目录下面 git 了 laradock
所以现在目录结构是   thinksns-plus/laradock
这样对的吗？

**Comment by medz** [comment]
这是单项目情况结构是对的 你要一个服务器跑多个程序 推荐把plus和 laradock 放在同一级 这样你进入工作区的 var/www/laradock/nginx/sites 下面增加一个配置即可增加一个网站

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月18日，16:43，jlala <notifications@github.com<mailto:notifications@github.com>> 写道：


还有一个地方请教下。
我在 thinksns-plus 这个目录下面 git 了 laradock
所以现在目录结构是 thinksns-plus/laradock
这样对的吗？

**Comment by jlala** [comment]
懂了 谢谢 收获不少。昨晚在今日头条看到的文章，今天实践了下，终于跑起来了。
我现在就是只能进入 后台。
前台只显示了 ThinkSNS+
我看介绍功能很多呀，怎么操作呢，还能有 feed 好多功能 app啥的？

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/27259625-943e8058-5449-11e7-957e-6cfa86b98fa7.png)
lei类似这种情况，我用 laradock 部署了两个网站

**Comment by medz** [comment]
其他功能需要安装拓展，其次 plus 的设计核心是 API。

**Comment by jlala** [comment]
嗯呢 我现在 把laradock目录移动到外面应该没问题吧？

其他功能安装拓展 怎么弄呢？现在能安装吗？

**Comment by medz** [comment]
可以移动，移动后进入工作空间的 var/www/laradock/nginx/sites下修改站点配置即可

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月18日，18:01，jlala <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯呢 我现在 把laradock目录移动到外面应该没问题吧？

其他功能安装拓展 怎么弄呢？现在能安装吗？
