### ISSUE TITLE
static header is overlapping the page content

### ISSUE THREAD

**Issue by AlaaAttyaMohamed** [zhiyicx/thinksns-plus#53]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
static header is overlapping the page content
<img width="1247" alt="screen shot 2017-06-19 at 9 38 56 am" src="https://user-images.githubusercontent.com/28359569/27274389-538ca38e-54d3-11e7-956a-552e25936bf5.png">

### Steps To Reproduce:

just open the home page

**Comment by medz** [comment]
ThinkSNS 4.x ? or http://demo.thinksns.com ? Can you describe the specific program?

**Comment by AlaaAttyaMohamed** [comment]
http://thinksns.com/index.html

i just opened the website and chose "translate to english" from chome

**Comment by medz** [comment]
Yeah, I know。
Thank you for your feedback, we have not made its URL to do the international treatment, Google translation of its Chinese website translated into English pages after the javascript rendering animation caused by the disorder.
