### ISSUE TITLE
【首页】当被其他设备登录后，再刷新原设备首页的“热门”与“最新”未调接口告知被另一设备登录

### ISSUE THREAD

**Issue by peicaichi** [zhiyicx/thinksns-plus#56]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

当被其他设备登录后，再刷新原设备首页的“热门”与“最新”未调接口告知被另一设备登录

### Steps To Reproduce:

A设备登录账号a-在B设备登录账号a-A设备首页的“热门”和“最新”进行下拉刷新
### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
目前认证token不完善，后续会重构～
