### ISSUE TITLE
composer require zhiyicx/plus-component-web问题

### ISSUE THREAD

**Issue by 1377195627** [zhiyicx/thinksns-plus#60]
composer require zhiyicx/plus-component-web输出下面的东西，而且require zhiyicx/plus-component-im也不行
Using version ^2.0 for zhiyicx/plus-component-web
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zhiyicx/plus-component-web ^2.0 -> satisfiable by zhiyicx/plus-component-web[2.0.0].
    - zhiyicx/plus-component-web 2.0.0 requires zhiyicx/plus-component-im ^2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by medz** [comment]
额～建议重新排版描述问题。。。

**Comment by boxshadow** [comment]
do you require zhiyicx/plus-component-im before you do this

**Comment by 1377195627** [comment]
require zhiyicx/plus-component-im 报错
                                                                                
  [InvalidArgumentException]                                                    
  Could not find package zhiyicx/plus-component-im at any version for your min  
  imum-stability (stable). Check the package spelling or your minimum-stabilit  
  y                                                                             
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by medz** [comment]
Try now
